---

- name: install misc dev brew applications
  homebrew: name={{ item }} state=latest
  with_items:
    - deno
    - elixir
    - ghc
    - go
    - haskell-stack

- name: install misc dev cask applications
  homebrew_cask: name={{ item }} state=present
  with_items:
    - supercollider
